#!/bin/sh

# All the other files in the if-up.d folder seem to have the above shebang instead of #!/bin/bash. Look into this and
# see if it works.

# This file will run once the jetsons connect to the internet. Its only for the purpose of running the git pull file
# script within our jetson-camera-code folder (I didn't look into how to run git fetch from a different folder) and
# this should be a quick fix.

# This follows the instructions here:
# https://askubuntu.com/questions/258580/how-to-run-a-script-depending-on-internet-connection

# Remember to give execution permission to this file in the if-up.d folder!

./home/tim/jetson-camera-code/run_on_internet_connection.sh